kind: Secret
apiVersion: v1
metadata:
  name: example-secret
  annotations:
    avp.kubernetes.io/path: "internal/data/database/config"
    avp.kubernetes.io/kv-version: "2"
type: Opaque
stringData:
  username: <username>
  password: <password>
